# Site
name: "Developers-Alliance Blog"
title: "Developers-Alliance Blog"
description: "Expert tips and insights from your certified development partners."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://blog.developers-alliance.com
google_analytics: 'G-JEDW9DKRRL'
disqus: 'developers-alliance-blog'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  David:
    name: David
    display_name: David
    gravatar: furryslowly788d1d4d48
    email: david@developers-alliance.com
    web: https://www.linkedin.com/in/david-tabatadze-981055213/
    description: "Magento & Adobe Commerce Master Architect | Full-Stack Web Developer | Passionate about building high-performance eCommerce solutions."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
